// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: 'enable',
  aws_cognito_identity_pool_id:
    'us-east-1:c5b13d37-7dea-4646-8806-a13af353ab60',
  aws_cognito_region: 'us-east-1',
  aws_content_delivery: 'enable',
  aws_content_delivery_bucket: 'cannaledgerwebdev-hosting-mobilehub-1392118238',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_cloudfront: 'enable',
  aws_content_delivery_cloudfront_domain: 'd2wegi17amgvst.cloudfront.net',
  aws_mobile_analytics_app_id: '4ff5a0bb861f4ee39fd87b737840846a',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_project_id: 'a4e9faf2-65e5-4d0d-80b6-07bbc3b43f9d',
  aws_project_name: 'cannaledger-web-dev',
  aws_project_region: 'us-east-1',
  aws_resource_name_prefix: 'cannaledgerwebdev-mobilehub-1392118238',
  aws_sign_in_enabled: 'enable',
  aws_user_pools: 'enable',
  aws_user_pools_id: 'us-east-1_edPvQdVZf',
  aws_user_pools_mfa_type: 'ON',
  aws_user_pools_web_client_id: '7e0gvrqbhq08p7d1ftpi4ivrpq',
};

export default awsmobile;
